name: Website
on:
  push:
    branches:
      - testnet3

jobs:
  deploy:
    name: SDK Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#        with:
#          persist-credentials: false

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-24
          override: true
          components: rustfmt, rust-src

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-website-${{ hashFiles('**/Cargo.lock') }}

      - name: Install and Build
        run: |
          rustup component add rust-src
          cd website
          yarn install
          yarn build
          cp _headers dist/_headers
        env:
          CI: ""

      - name: Deploy
        id: modified
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: website/dist
          clean-exclude: '["dev"]'

      - name: Check step output
        run: |
          [[ \
          ${{steps.modified.outputs.deployment-status}} = skipped || \
          ${{steps.modified.outputs.deployment-status}} = success \
          ]]

  benchmark:
    name: Benchmark
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      # Run benchmark and stores the output to a file
      - name: Benchmark
        run: |
          cargo bench --all | tee output.txt

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Aleo SDK Benchmarks
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.PAT_TOKEN }}
          auto-push: true
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@howardwu'
